/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export type ActualizarIdiomaAgenteBody = {
  /** El nuevo código de idioma a establecer */
  idioma: string;
};
