/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |
| 5006 | 200 | El plan no existe o no está habilitado para el usuario de la API |
| 5007 | 200 | El cliente no existe o no es del agente (ni de su agencia, si es administrador) |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.1.0
 */

export type ActualizarPerfilAgenteBody = {
  /** El nombre del agente, no puede quedar vacío (opcional) */
  nombre?: string;
  /** El apellido del agente, no puede quedar vacío (opcional) */
  apellido?: string;
  /** El teléfono del agente, cadena vacía para limpiarlo (opcional) */
  telefono?: string;
  /** El whatsapp del agente, cadena vacía para limpiarlo (opcional) */
  whatsapp?: string;
  /** ID del país del agente, de los que devuelve GET /{idioma}/paises (opcional) */
  pais?: number;
  /** Código del idioma del agente, de los que devuelve GET /idiomas (opcional) */
  idioma?: string;
  /** Correo alternativo para los avisos de renovación, cadena vacía para limpiarlo (opcional) */
  correo_renovaciones_alternativo?: string;
  /** Si el agente recibe o no los correos de renovación (opcional) */
  recibir_correos_renovaciones?: boolean;
};
