/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |
| 5006 | 200 | El plan no existe o no está habilitado para el usuario de la API |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.0.28
 */
import type { AgenciaItemTipo } from './agenciaItemTipo';
import type { AgenciaItemPadre } from './agenciaItemPadre';
import type { AgenciaItemPais } from './agenciaItemPais';
import type { AgenciaItemEstado } from './agenciaItemEstado';
import type { AgenciaItemCiudad } from './agenciaItemCiudad';
import type { AgenciaItemCodigoPostal } from './agenciaItemCodigoPostal';
import type { AgenciaItemSitioWeb } from './agenciaItemSitioWeb';
import type { AgenciaItemLogo } from './agenciaItemLogo';
import type { AgenciaItemTipoPago } from './agenciaItemTipoPago';
import type { AgenciaItemStatus } from './agenciaItemStatus';
import type { AgenciaItemCobrandingActivo } from './agenciaItemCobrandingActivo';

/**
 * Datos de una agencia con el formato uniforme de la API. Lo devuelve api_agencia_item() y es la base del perfil de agencia y del listado de agencias.
 */
export interface AgenciaItem {
  id?: number;
  /** Nombre de la agencia */
  nombre?: string;
  razon_social?: string;
  ruc?: string;
  /** Tipo de agencia, con el nombre en el idioma pedido */
  tipo?: AgenciaItemTipo;
  /** Agencia de la que depende */
  padre?: AgenciaItemPadre;
  /** País de la agencia */
  pais?: AgenciaItemPais;
  estado?: AgenciaItemEstado;
  ciudad?: AgenciaItemCiudad;
  direccion?: string;
  codigo_postal?: AgenciaItemCodigoPostal;
  telefono?: string;
  /** Persona de contacto de la agencia */
  contacto?: string;
  email?: string;
  /** Email secundario de la agencia. Recibe copia (CC/BCC según el correo) de lo que se le envía a `email`, cuando `email` está cargado; no se usa como fallback si `email` está vacío. */
  email_secundario?: string;
  sitio_web?: AgenciaItemSitioWeb;
  /** URL del logo de la agencia */
  logo?: AgenciaItemLogo;
  /** Porcentaje de comisión de la agencia */
  comision?: number;
  limite_credito?: string;
  meta_ventas_actual?: string;
  /** Tipo de pago, con el nombre en el idioma pedido */
  tipo_pago?: AgenciaItemTipoPago;
  /** Status de la agencia */
  status?: AgenciaItemStatus;
  /** Si la agencia puede crear agencias hijas */
  creador_agencias?: boolean;
  /** Si la agencia recibe copia de los vouchers emitidos */
  enviar_copia_vouchers?: boolean;
  paga_neta?: boolean;
  agentes_ven_neta?: boolean;
  permitir_sin_precio?: boolean;
  vouchers_sin_precio?: boolean;
  /** 1 si la agencia tiene cobranding activo */
  cobranding_activo?: AgenciaItemCobrandingActivo;
  /** Fecha del último login ya formateada, si la agencia la registra */
  ultimo_login_fecha?: string;
  /** Fecha de creación ya formateada */
  fecha_creacion?: string;
}
