/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.0.25
 */
import type { AgenteItemPais } from './agenteItemPais';
import type { AgenteItemAgencia } from './agenteItemAgencia';
import type { AgenteItemIdioma } from './agenteItemIdioma';
import type { AgenteItemTipoPago } from './agenteItemTipoPago';
import type { AgenteItemStatus } from './agenteItemStatus';
import type { AgenteItemEmailBienvenida } from './agenteItemEmailBienvenida';

/**
 * Datos de un agente con el formato uniforme de la API. Lo devuelve api_agente_item() y es la base de UserLogin y del listado de agentes, así que un agente se ve igual en todos los endpoints. El campo `rol` no se expone: el rol se lee en `roles`.
 */
export interface AgenteItem {
  id?: number;
  /** Código del agente */
  codigo?: string;
  /** Email del agente, que es además su usuario */
  email?: string;
  nombre?: string;
  apellido?: string;
  /** Nombre y apellido concatenados */
  nombre_completo?: string;
  telefono?: string;
  whatsapp?: string;
  /** País del agente */
  pais?: AgenteItemPais;
  /** Agencia a la que pertenece el agente */
  agencia?: AgenteItemAgencia;
  /** Código del idioma del agente */
  idioma?: AgenteItemIdioma;
  /** Porcentaje de comisión del agente */
  comision?: number;
  /** Roles del agente: agente, agente_administrador */
  roles?: string[];
  /** Tipo de pago, con el nombre en el idioma pedido */
  tipo_pago?: AgenteItemTipoPago;
  /** Status del agente, con el nombre en el idioma pedido */
  status?: AgenteItemStatus;
  recibir_correos_renovaciones?: boolean;
  correo_renovaciones_alternativo?: string;
  imagen?: string;
  /** URL del QR de descuentos del agente */
  qr?: string;
  /** Timestamp del último login */
  ultimo_login?: string;
  /** Fecha del último login ya formateada */
  ultimo_login_fecha?: string;
  /** Timestamp del correo de registro */
  email_registro?: string;
  /** Fecha del correo de registro ya formateada */
  email_registro_fecha?: string;
  /** Timestamp del correo de bienvenida, o null si no se envió */
  email_bienvenida?: AgenteItemEmailBienvenida;
  /** Fecha del correo de bienvenida ya formateada */
  email_bienvenida_fecha?: string;
  /** Fecha de creación ya formateada */
  fecha_creacion?: string;
}
