/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |
| 5006 | 200 | El plan no existe o no está habilitado para el usuario de la API |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.0.28
 */
import type { BusquedaItemTipo } from './busquedaItemTipo';

/**
 * Una coincidencia de la búsqueda. `tipo` dice de qué entidad es e `id` es su identificador, para pedir después el detalle.
 */
export interface BusquedaItem {
  /** La entidad a la que pertenece el resultado */
  tipo?: BusquedaItemTipo;
  /** ID de la entidad en su propia tabla */
  id?: number;
  /** La clave pública de la entidad, cuando tiene una: el voucher en las asistencias, el token del carrito en las cotizaciones y el pasaporte en los clientes. Vacía en agentes y agencias, que se identifican sólo por `id`. */
  referencia?: string;
  /** Texto principal para mostrar en la lista: el nombre completo en agentes y clientes, el nombre en agencias, el voucher en asistencias, y el nombre del cliente (o el token si todavía no tiene datos) en cotizaciones. */
  nombre?: string;
  /** Texto secundario para desambiguar, con las partes disponibles separadas por " · ". Puede venir vacío. */
  detalle?: string;
}
