/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetAsistenciasAgenteAgencia200DataItemsItemVouchersItem } from './getAsistenciasAgenteAgencia200DataItemsItemVouchersItem';

export type GetAsistenciasAgenteAgencia200DataItemsItem = {
  token?: string;
  total?: string;
  fecha?: string;
  vouchers?: GetAsistenciasAgenteAgencia200DataItemsItemVouchersItem[];
};
