/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetAsistenciasAgenteAgencia200Data } from './getAsistenciasAgenteAgencia200Data';

export type GetAsistenciasAgenteAgencia200 = {
  ok?: boolean;
  data?: GetAsistenciasAgenteAgencia200Data;
};
