/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemPdfVouchers } from './getAsistenciasAgenteAgencia200DataItemsItemVouchersItemPdfVouchers';
import type { GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEsItem } from './getAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEsItem';
import type { GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEnItem } from './getAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEnItem';

export type GetAsistenciasAgenteAgencia200DataItemsItemVouchersItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemPdfVouchers;
  links_tarjetas_es?: GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetAsistenciasAgenteAgencia200DataItemsItemVouchersItemLinksTarjetasEnItem[];
};
