/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetAsistenciasAgenteAgencia200DataItemsItem } from './getAsistenciasAgenteAgencia200DataItemsItem';
import type { GetAsistenciasAgenteAgencia200DataPaginacion } from './getAsistenciasAgenteAgencia200DataPaginacion';

export type GetAsistenciasAgenteAgencia200Data = {
  items?: GetAsistenciasAgenteAgencia200DataItemsItem[];
  paginacion?: GetAsistenciasAgenteAgencia200DataPaginacion;
};
