/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetAsistenciasAgenteAgencia200DataItemsItem } from './getAsistenciasAgenteAgencia200DataItemsItem';
import type { Paginacion } from './paginacion';

export type GetAsistenciasAgenteAgencia200Data = {
  items?: GetAsistenciasAgenteAgencia200DataItemsItem[];
  paginacion?: Paginacion;
};
