/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetAgentesAgencia200DataItem } from './getAgentesAgencia200DataItem';
import type { UserLogin } from './userLogin';

export type GetAgentesAgencia200 = {
  ok?: boolean;
  data?: GetAgentesAgencia200DataItem[];
  usuario?: UserLogin;
};
