/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export type GetAsistenciasAgenteAgenciaParams = {
/**
 * Número de página para paginación
 */
pagina?: number;
/**
 * Fecha de inicio para filtrar cotizaciones (formato DD/MM/YYYY)
 */
fecha_inicio?: string;
/**
 * Fecha de fin para filtrar cotizaciones (formato DD/MM/YYYY)
 */
fecha_final?: string;
};
