/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.0.25
 */
import type { GetAsistenciasAgenteAgencia200DataItemsItemVoucher } from './getAsistenciasAgenteAgencia200DataItemsItemVoucher';
import type { GetAsistenciasAgenteAgencia200DataItemsItemPlan } from './getAsistenciasAgenteAgencia200DataItemsItemPlan';
import type { GetAsistenciasAgenteAgencia200DataItemsItemVoucherMaster } from './getAsistenciasAgenteAgencia200DataItemsItemVoucherMaster';
import type { GetAsistenciasAgenteAgencia200DataItemsItemPaisOrigen } from './getAsistenciasAgenteAgencia200DataItemsItemPaisOrigen';
import type { GetAsistenciasAgenteAgencia200DataItemsItemPaisDestino } from './getAsistenciasAgenteAgencia200DataItemsItemPaisDestino';
import type { GetAsistenciasAgenteAgencia200DataItemsItemPagosItem } from './getAsistenciasAgenteAgencia200DataItemsItemPagosItem';
import type { GetAsistenciasAgenteAgencia200DataItemsItemPasajerosItem } from './getAsistenciasAgenteAgencia200DataItemsItemPasajerosItem';

export type GetAsistenciasAgenteAgencia200DataItemsItem = {
  token?: string;
  mostrar_precios?: boolean;
  total?: number;
  fecha?: string;
  voucher?: GetAsistenciasAgenteAgencia200DataItemsItemVoucher;
  plan?: GetAsistenciasAgenteAgencia200DataItemsItemPlan;
  voucher_master?: GetAsistenciasAgenteAgencia200DataItemsItemVoucherMaster;
  fecha_inicio?: string;
  fecha_fin?: string;
  pais_origen?: GetAsistenciasAgenteAgencia200DataItemsItemPaisOrigen;
  pais_destino?: GetAsistenciasAgenteAgencia200DataItemsItemPaisDestino;
  pagos?: GetAsistenciasAgenteAgencia200DataItemsItemPagosItem[];
  contacto?: string;
  contacto_telefono?: string;
  contacto_email?: string;
  consideraciones?: string;
  cancelada?: boolean;
  cancelada_fecha?: boolean;
  pasajeros?: GetAsistenciasAgenteAgencia200DataItemsItemPasajerosItem[];
};
