/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetAgenciasAgencia200DataItem } from './getAgenciasAgencia200DataItem';
import type { UserLogin } from './userLogin';

export type GetAgenciasAgencia200 = {
  ok?: boolean;
  data?: GetAgenciasAgencia200DataItem[];
  usuario?: UserLogin;
};
