/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetBuscarVoucher200DocumentosItemPdfVouchers } from './getBuscarVoucher200DocumentosItemPdfVouchers';
import type { GetBuscarVoucher200DocumentosItemLinksTarjetasEsItem } from './getBuscarVoucher200DocumentosItemLinksTarjetasEsItem';
import type { GetBuscarVoucher200DocumentosItemLinksTarjetasEnItem } from './getBuscarVoucher200DocumentosItemLinksTarjetasEnItem';

export type GetBuscarVoucher200DocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetBuscarVoucher200DocumentosItemPdfVouchers;
  links_tarjetas_es?: GetBuscarVoucher200DocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetBuscarVoucher200DocumentosItemLinksTarjetasEnItem[];
};
