/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export type GetBuscarVoucherParams = {
/**
 * El nombre del cliente
 */
nombre?: string;
/**
 * El apellido del cliente
 */
apellido?: string;
/**
 * El pasaporte del cliente
 */
pasaporte?: string;
/**
 * El número de voucher
 */
voucher?: string;
/**
 * La fecha de nacimiento del cliente (Formato dd/mm/yyyy)
 */
fecha_nacimiento?: string;
};
