/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetBuscarVoucher200DocumentosItem } from './getBuscarVoucher200DocumentosItem';
import type { User } from './user';

export type GetBuscarVoucher200 = {
  ok?: boolean;
  documentos?: GetBuscarVoucher200DocumentosItem[];
  user?: User;
};
