/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetCobrandingConfig200Datos } from './getCobrandingConfig200Datos';

export type GetCobrandingConfig200 = {
  ok?: boolean;
  datos?: GetCobrandingConfig200Datos;
};
