/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClientes200DataItemsItemVentas } from './getClientes200DataItemsItemVentas';

export type GetClientes200DataItemsItem = {
  id?: string;
  sexo?: string;
  pais_id?: string;
  pasaporte?: string;
  nombre?: string;
  apellido?: string;
  nacimiento_ts?: string;
  telefono?: string;
  email?: string;
  agente?: string;
  fecha_nacimiento?: string;
  pais_nombre?: string;
  sexo_nombre?: string;
  ventas?: GetClientes200DataItemsItemVentas;
};
