/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |
| 5006 | 200 | El plan no existe o no está habilitado para el usuario de la API |
| 5007 | 200 | El cliente no existe o no es del agente (ni de su agencia, si es administrador) |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.1.0
 */
import type { GetClientes200DataItemsItemSexo } from './getClientes200DataItemsItemSexo';
import type { GetClientes200DataItemsItemPaisId } from './getClientes200DataItemsItemPaisId';
import type { GetClientes200DataItemsItemAgente } from './getClientes200DataItemsItemAgente';
import type { GetClientes200DataItemsItemVentas } from './getClientes200DataItemsItemVentas';
import type { GetClientes200DataItemsItemPlanesActivosItem } from './getClientes200DataItemsItemPlanesActivosItem';

export type GetClientes200DataItemsItem = {
  id?: number;
  sexo?: GetClientes200DataItemsItemSexo;
  /** País del cliente */
  pais_id?: GetClientes200DataItemsItemPaisId;
  pasaporte?: string;
  nombre?: string;
  apellido?: string;
  telefono?: string;
  email?: string;
  /** Agente que registró al cliente */
  agente?: GetClientes200DataItemsItemAgente;
  fecha_nacimiento?: string;
  /** Resumen de todas las ventas de la persona (mismo pasaporte y país), del agente o de toda la agencia si es administrador */
  ventas?: GetClientes200DataItemsItemVentas;
  /** Ventas no canceladas del cliente cuya vigencia incluye el día de hoy, del agente o de toda la agencia si es administrador */
  planes_activos?: GetClientes200DataItemsItemPlanesActivosItem[];
};
