/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClienteVentas200DataItemsItem } from './getClienteVentas200DataItemsItem';
import type { Paginacion } from './paginacion';

export type GetClienteVentas200Data = {
  items?: GetClienteVentas200DataItemsItem[];
  paginacion?: Paginacion;
};
