/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClienteVentas200Data } from './getClienteVentas200Data';
import type { User } from './user';

export type GetClienteVentas200 = {
  ok?: boolean;
  data?: GetClienteVentas200Data;
  usuario?: User;
};
