/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClienteVentas200DataItemsItemDocumentosItem } from './getClienteVentas200DataItemsItemDocumentosItem';

export type GetClienteVentas200DataItemsItem = {
  voucher?: string;
  precio?: string;
  fecha?: string;
  total?: string;
  documentos?: GetClienteVentas200DataItemsItemDocumentosItem[];
};
