/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export type GetCobrandingConfig200Datos = {
  id?: string;
  agencia?: string;
  agente?: string;
  color1?: string;
  color2?: string;
  color3?: string;
  color4?: string;
  logo?: string;
  home_sec1_img?: string;
  home_sec3_img1?: string;
  home_sec3_img2?: string;
  home_sec3_img3?: string;
  home_bg_form?: string;
  /** @nullable */
  telefono?: string | null;
  /** @nullable */
  whatsapp?: string | null;
  /** @nullable */
  email?: string | null;
  nombre?: string;
  dominio?: string;
  home_titulo?: string;
  home_subtitulo?: string;
  home_cta1?: string;
  home_sec2_titulo?: string;
  home_sec2_subtitulo?: string;
  home_sec3_titulo?: string;
  home_sec3_subtitulo1?: string;
  home_sec3_texto1?: string;
  home_sec3_subtitulo2?: string;
  home_sec3_texto2?: string;
  home_sec3_subtitulo3?: string;
  home_sec3_texto3?: string;
  home_sec3_cta?: string;
  home_sec4_titulo?: string;
  home_sec4_texto?: string;
  footer_col?: string;
  planes?: string[];
  tipos_planes?: string[];
};
