/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetCotizacionesAgenteAgencia200DataItemsItem } from './getCotizacionesAgenteAgencia200DataItemsItem';
import type { GetCotizacionesAgenteAgencia200DataPaginacion } from './getCotizacionesAgenteAgencia200DataPaginacion';

export type GetCotizacionesAgenteAgencia200Data = {
  items?: GetCotizacionesAgenteAgencia200DataItemsItem[];
  paginacion?: GetCotizacionesAgenteAgencia200DataPaginacion;
};
