/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClienteVentas200DataItemsItemDocumentosItemPdfVouchers } from './getClienteVentas200DataItemsItemDocumentosItemPdfVouchers';
import type { GetClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEsItem } from './getClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEsItem';
import type { GetClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEnItem } from './getClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEnItem';

export type GetClienteVentas200DataItemsItemDocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetClienteVentas200DataItemsItemDocumentosItemPdfVouchers;
  links_tarjetas_es?: GetClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetClienteVentas200DataItemsItemDocumentosItemLinksTarjetasEnItem[];
};
