/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetCobrandingConfig200DatosDescripcionesTiposPlanes } from './getCobrandingConfig200DatosDescripcionesTiposPlanes';

export type GetCobrandingConfig200Datos = {
  id?: string;
  agencia?: string;
  agente?: string;
  color1?: string;
  color2?: string;
  color3?: string;
  color4?: string;
  logo?: string;
  logo_size?: string;
  fuente1?: string;
  fuente2?: string;
  icono?: string;
  meta_description?: string;
  counter1_value?: string;
  counter1_append?: string;
  counter1_texto?: string;
  counter2_value?: string;
  counter2_append?: string;
  counter2_texto?: string;
  home_sec1_img?: string;
  /** @nullable */
  home_sec3_img1?: string | null;
  /** @nullable */
  home_sec3_img2?: string | null;
  /** @nullable */
  home_sec3_img3?: string | null;
  home_bg_form?: string;
  /** @nullable */
  telefono?: string | null;
  whatsapp?: string;
  email?: string;
  nombre?: string;
  dominio?: string;
  home_titulo?: string;
  home_subtitulo?: string;
  home_cta1?: string;
  home_sec2_titulo?: string;
  home_sec2_subtitulo?: string;
  home_sec3_titulo?: string;
  home_sec3_subtitulo1?: string;
  home_sec3_texto1?: string;
  home_sec3_subtitulo2?: string;
  home_sec3_texto2?: string;
  home_sec3_subtitulo3?: string;
  home_sec3_texto3?: string;
  home_sec3_cta?: string;
  home_sec4_titulo?: string;
  home_sec4_texto?: string;
  footer_col?: string;
  planes?: string[];
  tipos_planes?: string[];
  /** Descripciones de cada tipo de plan, keyeado por ID del tipo de plan */
  descripciones_tipos_planes?: GetCobrandingConfig200DatosDescripcionesTiposPlanes;
};
