/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClientes200Data } from './getClientes200Data';

export type GetClientes200 = {
  ok?: boolean;
  data?: GetClientes200Data;
};
