/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.

## Errores

Todas las respuestas de error salen en JSON con la misma forma: `ok` en `false`, un `mensaje` para mostrar y un `error_code` para decidir en el front.

| error_code | HTTP | Cuándo |
| --- | --- | --- |
| 5000 | 302 | Falta el token de la API o no es válido (header `Authorization: Bearer`) |
| 5001 | 200 | El idioma del path no está soportado |
| 5002 | 200 | El `userToken` del agente no es válido o expiró |
| 5003 | 404 | El endpoint solicitado no existe |
| 5004 | 405 | El método HTTP no está permitido para ese endpoint |
| 5005 | 500 | Error interno al procesar la solicitud |
| 5006 | 200 | El plan no existe o no está habilitado para el usuario de la API |
| 5007 | 200 | El cliente no existe o no es del agente (ni de su agencia, si es administrador) |

Los códigos 5001 y 5002 son de negocio y viajan con HTTP 200: hay que mirar siempre el campo `ok`, no sólo el status.

Los códigos 5003, 5004 y 5005 los resuelve el manejador global, así que pueden aparecer en cualquier endpoint.

Cuando el error es de validación de campos, además de `error` viene `errores`, un objeto con un motivo por campo (`requerido`, `invalido`, `duplicado`, `excede_comision_agencia`, `no_permitido`).

En el ambiente de desarrollo las respuestas 500 agregan `error` y `archivo` con el detalle técnico; en producción no.

 * OpenAPI spec version: 1.1.0
 */
import type { GetCobrandingConfig200DatosHomeSec3Img1 } from './getCobrandingConfig200DatosHomeSec3Img1';
import type { GetCobrandingConfig200DatosHomeSec3Img2 } from './getCobrandingConfig200DatosHomeSec3Img2';
import type { GetCobrandingConfig200DatosHomeSec3Img3 } from './getCobrandingConfig200DatosHomeSec3Img3';
import type { GetCobrandingConfig200DatosTelefono } from './getCobrandingConfig200DatosTelefono';
import type { GetCobrandingConfig200DatosDescripcionesTiposPlanes } from './getCobrandingConfig200DatosDescripcionesTiposPlanes';

export type GetCobrandingConfig200Datos = {
  id?: string;
  agencia?: string;
  agente?: string;
  color1?: string;
  color2?: string;
  color3?: string;
  color4?: string;
  logo?: string;
  logo_size?: string;
  fuente1?: string;
  fuente2?: string;
  icono?: string;
  meta_description?: string;
  counter1_value?: string;
  counter1_append?: string;
  counter1_texto?: string;
  counter2_value?: string;
  counter2_append?: string;
  counter2_texto?: string;
  home_sec1_img?: string;
  home_sec3_img1?: GetCobrandingConfig200DatosHomeSec3Img1;
  home_sec3_img2?: GetCobrandingConfig200DatosHomeSec3Img2;
  home_sec3_img3?: GetCobrandingConfig200DatosHomeSec3Img3;
  home_bg_form?: string;
  telefono?: GetCobrandingConfig200DatosTelefono;
  whatsapp?: string;
  email?: string;
  nombre?: string;
  dominio?: string;
  home_titulo?: string;
  home_subtitulo?: string;
  home_cta1?: string;
  home_sec2_titulo?: string;
  home_sec2_subtitulo?: string;
  home_sec3_titulo?: string;
  home_sec3_subtitulo1?: string;
  home_sec3_texto1?: string;
  home_sec3_subtitulo2?: string;
  home_sec3_texto2?: string;
  home_sec3_subtitulo3?: string;
  home_sec3_texto3?: string;
  home_sec3_cta?: string;
  home_sec4_titulo?: string;
  home_sec4_texto?: string;
  footer_col?: string;
  planes?: string[];
  tipos_planes?: string[];
  /** Descripciones de cada tipo de plan, keyeado por ID del tipo de plan */
  descripciones_tipos_planes?: GetCobrandingConfig200DatosDescripcionesTiposPlanes;
};
