/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClientesSort } from './getClientesSort';
import type { GetClientesSortOrder } from './getClientesSortOrder';

export type GetClientesParams = {
/**
 * Número de página para paginación
 */
pagina?: number;
/**
 * Campo por el cual ordenar
 */
sort?: GetClientesSort;
/**
 * Orden de clasificación
 */
sort_order?: GetClientesSortOrder;
};
