/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export type GetCotizacionesAgenteAgencia200DataPaginacion = {
  pagina_actual?: number;
  cantidad_paginas?: number;
  cantidad_total?: number;
};
