/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

/**
 * Descripciones de cada tipo de plan, keyeado por ID del tipo de plan
 */
export type GetCobrandingConfig200DatosDescripcionesTiposPlanes = {[key: string]: string};
