/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetClientes200DataItemsItem } from './getClientes200DataItemsItem';
import type { Paginacion } from './paginacion';

export type GetClientes200Data = {
  items?: GetClientes200DataItemsItem[];
  paginacion?: Paginacion;
};
