/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetDashboard200DataRenovaciones } from './getDashboard200DataRenovaciones';
import type { GetDashboard200DataTopPlanesItem } from './getDashboard200DataTopPlanesItem';
import type { GetDashboard200DataKpis } from './getDashboard200DataKpis';
import type { GetDashboard200DataComisionesItem } from './getDashboard200DataComisionesItem';

export type GetDashboard200Data = {
  renovaciones?: GetDashboard200DataRenovaciones;
  top_planes?: GetDashboard200DataTopPlanesItem[];
  kpis?: GetDashboard200DataKpis;
  comisiones?: GetDashboard200DataComisionesItem[];
  meta_ventas_mensual?: number;
};
