/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetDocumentosVoucher200DocumentosItem } from './getDocumentosVoucher200DocumentosItem';
import type { User } from './user';

export type GetDocumentosVoucher200 = {
  ok?: boolean;
  documentos?: GetDocumentosVoucher200DocumentosItem[];
  user?: User;
};
