/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetDashboard200Data } from './getDashboard200Data';
import type { UserLogin } from './userLogin';

export type GetDashboard200 = {
  ok?: boolean;
  data?: GetDashboard200Data;
  usuario?: UserLogin;
};
