/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export type GetDocumentosVoucher200DocumentosItemPdfVouchers = {
  es?: string;
  en?: string;
};
