/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export type GetDashboard200DataKpisVentasMes = {
  cantidad_ventas?: number;
  cantidad_vouchers?: number;
  clientes?: number;
  monto?: number;
  ticket_promedio?: number;
  nombre?: string;
};
