/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetDashboard200DataKpisVentas } from './getDashboard200DataKpisVentas';

export type GetDashboard200DataKpis = {
  ventas?: GetDashboard200DataKpisVentas;
};
