/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetDocumentosVoucher200DocumentosItemPdfVouchers } from './getDocumentosVoucher200DocumentosItemPdfVouchers';
import type { GetDocumentosVoucher200DocumentosItemLinksTarjetasEsItem } from './getDocumentosVoucher200DocumentosItemLinksTarjetasEsItem';
import type { GetDocumentosVoucher200DocumentosItemLinksTarjetasEnItem } from './getDocumentosVoucher200DocumentosItemLinksTarjetasEnItem';

export type GetDocumentosVoucher200DocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetDocumentosVoucher200DocumentosItemPdfVouchers;
  links_tarjetas_es?: GetDocumentosVoucher200DocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetDocumentosVoucher200DocumentosItemLinksTarjetasEnItem[];
};
