/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetDashboard200DataRenovacionesPendientes } from './getDashboard200DataRenovacionesPendientes';
import type { GetDashboard200DataRenovacionesCompletadas } from './getDashboard200DataRenovacionesCompletadas';

export type GetDashboard200DataRenovaciones = {
  pendientes?: GetDashboard200DataRenovacionesPendientes;
  completadas?: GetDashboard200DataRenovacionesCompletadas;
};
