/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { Respuesta } from './respuesta';

export type GetIdiomaDocumentosVoucher200 = {
  ok?: boolean;
  data?: Respuesta;
};
