/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */

export type GetIdiomaAgentesParams = {
/**
 * ID de la agencia para filtrar los agentes
 */
agencia: number;
};
