/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaAgentes200DataItem } from './getIdiomaAgentes200DataItem';
import type { UserLogin } from './userLogin';

export type GetIdiomaAgentes200 = {
  ok?: boolean;
  data?: GetIdiomaAgentes200DataItem[];
  usuario?: UserLogin;
};
