/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers } from './getIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers';
import type { GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem } from './getIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem';
import type { GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem } from './getIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem';

export type GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers;
  links_tarjetas_es?: GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetIdiomaRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem[];
};
