/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaDocumentosVoucher200DocumentosItem } from './getIdiomaDocumentosVoucher200DocumentosItem';
import type { User } from './user';

export type GetIdiomaDocumentosVoucher200 = {
  ok?: boolean;
  documentos?: GetIdiomaDocumentosVoucher200DocumentosItem[];
  user?: User;
};
