/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { Respuesta } from './respuesta';
import type { GetIdiomaTiposPlanes200User } from './getIdiomaTiposPlanes200User';

export type GetIdiomaTiposPlanes200 = {
  ok?: boolean;
  data?: Respuesta;
  /**
   * Datos del agente autenticado, si aplica
   * @nullable
   */
  user?: GetIdiomaTiposPlanes200User;
};
