/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaDocumentosVoucher200DocumentosItemPdfVouchers } from './getIdiomaDocumentosVoucher200DocumentosItemPdfVouchers';
import type { GetIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEsItem } from './getIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEsItem';
import type { GetIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEnItem } from './getIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEnItem';

export type GetIdiomaDocumentosVoucher200DocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetIdiomaDocumentosVoucher200DocumentosItemPdfVouchers;
  links_tarjetas_es?: GetIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetIdiomaDocumentosVoucher200DocumentosItemLinksTarjetasEnItem[];
};
