/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaAsistenciasPagina200DataItemsItem } from './getIdiomaAsistenciasPagina200DataItemsItem';
import type { GetIdiomaAsistenciasPagina200DataPaginacion } from './getIdiomaAsistenciasPagina200DataPaginacion';

export type GetIdiomaAsistenciasPagina200Data = {
  items?: GetIdiomaAsistenciasPagina200DataItemsItem[];
  paginacion?: GetIdiomaAsistenciasPagina200DataPaginacion;
};
