/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */

export type GetIdiomaVouchersMasterIdMaster200DataVoucher = {
  id?: string;
  codigo?: string;
  agencia?: string;
  agente?: string;
  plan?: string;
  noches?: string;
  noches_disponibles?: string;
  precio?: string;
  costo_procesamiento?: string;
  precio_dia?: string;
  costo_dia?: string;
  ts_ini?: string;
  ts_fin?: string;
  ts_creacion?: string;
  ts_emision?: string;
  comision_procesada?: string;
  status?: string;
};
