/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaCotizaciones200DataItemsItem } from './getIdiomaCotizaciones200DataItemsItem';
import type { GetIdiomaCotizaciones200DataPaginacion } from './getIdiomaCotizaciones200DataPaginacion';

export type GetIdiomaCotizaciones200Data = {
  items?: GetIdiomaCotizaciones200DataItemsItem[];
  paginacion?: GetIdiomaCotizaciones200DataPaginacion;
};
