/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemPdfVouchers } from './getIdiomaAsistenciasPagina200DataItemsItemVouchersItemPdfVouchers';
import type { GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEsItem } from './getIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEsItem';
import type { GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEnItem } from './getIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEnItem';

export type GetIdiomaAsistenciasPagina200DataItemsItemVouchersItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemPdfVouchers;
  links_tarjetas_es?: GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetIdiomaAsistenciasPagina200DataItemsItemVouchersItemLinksTarjetasEnItem[];
};
