/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaAsistenciasPagina200Data } from './getIdiomaAsistenciasPagina200Data';

export type GetIdiomaAsistenciasPagina200 = {
  ok?: boolean;
  data?: GetIdiomaAsistenciasPagina200Data;
};
