/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaLangStringsVersion200Data } from './getIdiomaLangStringsVersion200Data';

export type GetIdiomaLangStringsVersion200 = {
  ok?: boolean;
  data?: GetIdiomaLangStringsVersion200Data;
};
