/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaAsistenciasPagina200DataItemsItemVouchersItem } from './getIdiomaAsistenciasPagina200DataItemsItemVouchersItem';

export type GetIdiomaAsistenciasPagina200DataItemsItem = {
  token?: string;
  total?: string;
  fecha?: string;
  vouchers?: GetIdiomaAsistenciasPagina200DataItemsItemVouchersItem[];
};
