/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaRenovacionesPendientes200Data } from './getIdiomaRenovacionesPendientes200Data';
import type { UserLogin } from './userLogin';

export type GetIdiomaRenovacionesPendientes200 = {
  ok?: boolean;
  data?: GetIdiomaRenovacionesPendientes200Data;
  usuario?: UserLogin;
};
