/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaVouchersMasterIdMaster200DataVoucher } from './getIdiomaVouchersMasterIdMaster200DataVoucher';
import type { GetIdiomaVouchersMasterIdMaster200DataItemsItem } from './getIdiomaVouchersMasterIdMaster200DataItemsItem';

export type GetIdiomaVouchersMasterIdMaster200Data = {
  voucher?: GetIdiomaVouchersMasterIdMaster200DataVoucher;
  /** Lista de vouchers creados bajo este master */
  items?: GetIdiomaVouchersMasterIdMaster200DataItemsItem[];
};
