/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaRenovacionesPendientes200DataItemsItem } from './getIdiomaRenovacionesPendientes200DataItemsItem';

export type GetIdiomaRenovacionesPendientes200Data = {
  items?: GetIdiomaRenovacionesPendientes200DataItemsItem[];
};
