/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { GetIdiomaVouchersMasterIdMaster200Data } from './getIdiomaVouchersMasterIdMaster200Data';
import type { UserLogin } from './userLogin';

export type GetIdiomaVouchersMasterIdMaster200 = {
  ok?: boolean;
  data?: GetIdiomaVouchersMasterIdMaster200Data;
  usuario?: UserLogin;
};
