/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetLangStringsVersion200Data } from './getLangStringsVersion200Data';

export type GetLangStringsVersion200 = {
  ok?: boolean;
  data?: GetLangStringsVersion200Data;
};
