/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

/**
 * Datos del lead del evento
 */
export type GetLeadEventoBody = {
  evento?: string;
  nombre?: string;
  apellido?: string;
  ocupacion?: string;
  email?: string;
  telefono?: string;
  ip?: string;
};
