/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetLangStrings200Data } from './getLangStrings200Data';

export type GetLangStrings200 = {
  ok?: boolean;
  data?: GetLangStrings200Data;
};
