/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetPerfilAgencia200Data } from './getPerfilAgencia200Data';
import type { UserLogin } from './userLogin';

export type GetPerfilAgencia200 = {
  ok?: boolean;
  data?: GetPerfilAgencia200Data;
  usuario?: UserLogin;
};
