/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export type GetPerfilAgencia200Data = {
  id?: string;
  nombre?: string;
  comision?: string;
  creador_agencias?: boolean;
  padre?: string;
  razon_social?: string;
  ruc?: string;
  pais?: string;
  /** @nullable */
  estado?: string | null;
  /** @nullable */
  ciudad?: string | null;
  direccion?: string;
  /** @nullable */
  codigo_postal?: string | null;
  telefono?: string;
  contacto?: string;
  email?: string;
  /** @nullable */
  sitio_web?: string | null;
  enviar_copia_vouchers?: boolean;
  /** @nullable */
  logo?: string | null;
  limite_credito?: string;
  paga_neta?: boolean;
  agentes_ven_neta?: boolean;
  tipo_pago?: string;
  permitir_sin_precio?: boolean;
  vouchers_sin_precio?: boolean;
  status?: string;
  nombre_padre?: string;
  pais_nombre?: string;
  ultimo_login_fecha?: string;
  tipo_pago_nombre?: string;
  fecha_creacion?: string;
  tipo?: string;
  tipo_nombre?: string;
};
