/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers } from './getRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers';
import type { GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem } from './getRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem';
import type { GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem } from './getRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem';

export type GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItem = {
  nombre?: string;
  voucher?: string;
  pdf_vouchers?: GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemPdfVouchers;
  links_tarjetas_es?: GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEsItem[];
  links_tarjetas_en?: GetRenovacionesPendientes200DataItemsItemVentaDatosDocumentosItemLinksTarjetasEnItem[];
};
