/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetRenovacionesPendientes200DataItemsItem } from './getRenovacionesPendientes200DataItemsItem';

export type GetRenovacionesPendientes200Data = {
  items?: GetRenovacionesPendientes200DataItemsItem[];
};
