/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetRenovacionesPendientes200DataItemsItemVentaDatos } from './getRenovacionesPendientes200DataItemsItemVentaDatos';

export type GetRenovacionesPendientes200DataItemsItem = {
  id?: string;
  venta?: string;
  agente?: string;
  agencia?: string;
  carrito?: string;
  carrito_linea?: string;
  precio_total?: string;
  ts_creacion?: string;
  ts_inicio_viaje?: string;
  ultimo_recordatorio?: string;
  /** @nullable */
  venta_renovacion?: string | null;
  /** @nullable */
  ts_cierre?: string | null;
  idioma?: string;
  status?: string;
  agente_nombre?: string;
  agencia_nombre?: string;
  fecha_inicio_viaje?: string;
  /** @nullable */
  etapa_nombre?: string | null;
  venta_datos?: GetRenovacionesPendientes200DataItemsItemVentaDatos;
  url_carrito?: string;
};
