/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetRenovacionesPendientes200Data } from './getRenovacionesPendientes200Data';
import type { UserLogin } from './userLogin';

export type GetRenovacionesPendientes200 = {
  ok?: boolean;
  data?: GetRenovacionesPendientes200Data;
  usuario?: UserLogin;
};
