/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetStatusCodes200DataGenericosItem } from './getStatusCodes200DataGenericosItem';
import type { GetStatusCodes200DataCarritosItem } from './getStatusCodes200DataCarritosItem';
import type { GetStatusCodes200DataRenovacionesItem } from './getStatusCodes200DataRenovacionesItem';

export type GetStatusCodes200Data = {
  genericos?: GetStatusCodes200DataGenericosItem[];
  carritos?: GetStatusCodes200DataCarritosItem[];
  renovaciones?: GetStatusCodes200DataRenovacionesItem[];
};
