/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetStatusCodes200Data } from './getStatusCodes200Data';

export type GetStatusCodes200 = {
  ok?: boolean;
  data?: GetStatusCodes200Data;
};
