/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import type { GetTasaComisiones200DataItem } from './getTasaComisiones200DataItem';

export type GetTasaComisiones200 = {
  ok?: boolean;
  /** Lista de tipos de plan con su comisión porcentual */
  data?: GetTasaComisiones200DataItem[];
};
