/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export type GetVouchersMasterDetail200DataItemsItem = {
  id?: string;
  linea_carrito?: string;
  pais?: string;
  pais_destino?: string;
  plan?: string;
  distribuidor?: string;
  agente?: string;
  precio?: string;
  costo?: string;
  costo_base?: string;
  costo_transaccion?: string;
  margen?: string;
  fecha_ts?: string;
  fecha_inicio_ts?: string;
  fecha_fin_ts?: string;
  voucher?: string;
  voucher_master?: string;
  ocultar_precios?: string;
  enviar_correos?: string;
  contacto?: string;
  contacto_telefono?: string;
  contacto_email?: string;
  consideraciones?: string;
  cancelada?: string;
  /** @nullable */
  fecha_cancelacion_ts?: string | null;
  usuario_cancelacion?: string;
  /** @nullable */
  cobrada_recibo?: string | null;
  /** @nullable */
  pagada_cheque?: string | null;
  metodo_pago?: string;
  pais_bin?: string;
  transaccion_internacional?: string;
  comision_procesada?: string;
  /** @nullable */
  renovacion_de?: string | null;
  leido_erp?: string;
  aprobacion_temp?: string;
  noches?: number;
};
