/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetVouchersMaster200DataItem } from './getVouchersMaster200DataItem';

export type GetVouchersMaster200 = {
  ok?: boolean;
  data?: GetVouchersMaster200DataItem[];
};
