/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetVouchersMasterDetail200DataVoucher } from './getVouchersMasterDetail200DataVoucher';
import type { GetVouchersMasterDetail200DataItemsItem } from './getVouchersMasterDetail200DataItemsItem';

export type GetVouchersMasterDetail200Data = {
  voucher?: GetVouchersMasterDetail200DataVoucher;
  /** Lista de vouchers creados bajo este master */
  items?: GetVouchersMasterDetail200DataItemsItem[];
};
