/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { GetVouchersMasterDetail200Data } from './getVouchersMasterDetail200Data';
import type { UserLogin } from './userLogin';

export type GetVouchersMasterDetail200 = {
  ok?: boolean;
  data?: GetVouchersMasterDetail200Data;
  usuario?: UserLogin;
};
