/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export interface Paginacion {
  pagina_actual?: number;
  cantidad_paginas?: number;
  cantidad_total?: number;
  por_pagina?: number;
}
