/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */

export type PostAgenteLoginBody = {
  /** El email del usuario */
  user?: string;
  /** La contraseña del usuario */
  pw?: string;
  /** ID de la agencia (opcional) */
  id_agencia?: string;
};
