/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { PostIdiomaLogin200Data } from './postIdiomaLogin200Data';

export type PostIdiomaLogin200 = {
  ok?: boolean;
  data?: PostIdiomaLogin200Data;
};
