/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */
import type { ReporteVentasAgenciaResponseData } from './reporteVentasAgenciaResponseData';

export interface ReporteVentasAgenciaResponse {
  ok?: boolean;
  data?: ReporteVentasAgenciaResponseData;
}
