/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import type { ReporteVentasAgenciaResponseDataItemsItem } from './reporteVentasAgenciaResponseDataItemsItem';
import type { ReporteVentasAgenciaResponseDataAcums } from './reporteVentasAgenciaResponseDataAcums';

export type ReporteVentasAgenciaResponseData = {
  mes?: string;
  mes_nombre?: string;
  ano?: string;
  /** ID de la agencia */
  agencia?: string;
  agente?: number;
  items?: ReporteVentasAgenciaResponseDataItemsItem[];
  acums?: ReporteVentasAgenciaResponseDataAcums;
};
