/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */

export type UserAgente = {
  nombre?: string;
  apellido?: string;
  email?: string;
  codigo?: string;
  comision?: string;
};
