/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.1
 */

export interface UserLogin {
  id?: string;
  email?: string;
  /** @nullable */
  pais?: string | null;
  nombre?: string;
  apellido?: string;
  telefono?: string;
  whatsapp?: string;
  ultimo_login?: string;
  imagen?: string;
  distribuidor?: string;
  comision?: string;
  cambiar_password?: string;
  rol?: string;
  tipo_pago?: string;
  qr?: string;
  recibir_correos_renovaciones?: boolean;
  correo_renovaciones_alternativo?: string;
  status?: string;
  userid?: string;
  nombre_completo?: string;
  cambiarpassword?: boolean;
  agencia?: string;
  /** @nullable */
  idioma_user?: string | null;
  token_api?: string;
  roles?: string[];
}
