/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.16
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  ActualizarIdiomaAgente200,
  ActualizarIdiomaAgenteBody,
  DetenerRecordatorioRenovacion200,
  DetenerRecordatorioRenovacionBody,
  GetAgenciasAgencia200,
  GetAgentesAgencia200,
  GetAgentesAgenciaParams,
  GetAsistenciasAgenteAgencia200,
  GetAsistenciasAgenteAgenciaParams,
  GetBuscarVoucher200,
  GetBuscarVoucherParams,
  GetClienteVentas200,
  GetClienteVentasParams,
  GetClientes200,
  GetClientesParams,
  GetCobrandingConfig200,
  GetCobrandingConfigBody,
  GetCotizacionesAgenteAgencia200,
  GetCotizacionesAgenteAgenciaParams,
  GetDashboard200,
  GetDocumentosVoucher200,
  GetIdiomas200,
  GetLangStrings200,
  GetLangStringsVersion200,
  GetLeadEvento200,
  GetLeadEventoBody,
  GetPerfilAgencia200,
  GetPerfilAgente200,
  GetRenovacionesPendientes200,
  GetStatusCodes200,
  GetTasaComisiones200,
  GetVouchersMaster200,
  GetVouchersMasterDetail200,
  PostAgenteLogin200,
  PostAgenteLoginBody,
  PostLogout200,
  ReporteVentasAgenciaResponse
} from './schemas';

import { customFetch } from './custom-fetcher';




/**
 * Los idiomas que tiene el Sitio
 * @summary Listado de Idiomas
 */
export const getIdiomas = (
    
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetIdiomas200>(
      {url: `/idiomas`, method: 'GET', signal
    },
      );
    }
  

export const getGetIdiomasQueryKey = () => {
    return [`/idiomas`] as const;
    }

    
export const getGetIdiomasQueryOptions = <TData = Awaited<ReturnType<typeof getIdiomas>>, TError = null | null>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetIdiomasQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getIdiomas>>> = ({ signal }) => getIdiomas(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetIdiomasQueryResult = NonNullable<Awaited<ReturnType<typeof getIdiomas>>>
export type GetIdiomasQueryError = null | null


export function useGetIdiomas<TData = Awaited<ReturnType<typeof getIdiomas>>, TError = null | null>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIdiomas>>,
          TError,
          Awaited<ReturnType<typeof getIdiomas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIdiomas<TData = Awaited<ReturnType<typeof getIdiomas>>, TError = null | null>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getIdiomas>>,
          TError,
          Awaited<ReturnType<typeof getIdiomas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetIdiomas<TData = Awaited<ReturnType<typeof getIdiomas>>, TError = null | null>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listado de Idiomas
 */

export function useGetIdiomas<TData = Awaited<ReturnType<typeof getIdiomas>>, TError = null | null>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getIdiomas>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetIdiomasQueryOptions(options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Muestra la última versión de las traducciones del idioma
 * @summary Última versión de las traducciones
 */
export const getLangStringsVersion = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetLangStringsVersion200>(
      {url: `/${idioma}/lang_strings_version`, method: 'GET', signal
    },
      );
    }
  

export const getGetLangStringsVersionQueryKey = (idioma?: string,) => {
    return [`/${idioma}/lang_strings_version`] as const;
    }

    
export const getGetLangStringsVersionQueryOptions = <TData = Awaited<ReturnType<typeof getLangStringsVersion>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLangStringsVersionQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLangStringsVersion>>> = ({ signal }) => getLangStringsVersion(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLangStringsVersionQueryResult = NonNullable<Awaited<ReturnType<typeof getLangStringsVersion>>>
export type GetLangStringsVersionQueryError = null | null


export function useGetLangStringsVersion<TData = Awaited<ReturnType<typeof getLangStringsVersion>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLangStringsVersion>>,
          TError,
          Awaited<ReturnType<typeof getLangStringsVersion>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLangStringsVersion<TData = Awaited<ReturnType<typeof getLangStringsVersion>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLangStringsVersion>>,
          TError,
          Awaited<ReturnType<typeof getLangStringsVersion>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLangStringsVersion<TData = Awaited<ReturnType<typeof getLangStringsVersion>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Última versión de las traducciones
 */

export function useGetLangStringsVersion<TData = Awaited<ReturnType<typeof getLangStringsVersion>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStringsVersion>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLangStringsVersionQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Muestra las traducciones del idioma seleccionado
 * @summary Traducciones
 */
export const getLangStrings = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetLangStrings200>(
      {url: `/${idioma}/lang_strings`, method: 'GET', signal
    },
      );
    }
  

export const getGetLangStringsQueryKey = (idioma?: string,) => {
    return [`/${idioma}/lang_strings`] as const;
    }

    
export const getGetLangStringsQueryOptions = <TData = Awaited<ReturnType<typeof getLangStrings>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetLangStringsQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getLangStrings>>> = ({ signal }) => getLangStrings(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetLangStringsQueryResult = NonNullable<Awaited<ReturnType<typeof getLangStrings>>>
export type GetLangStringsQueryError = null | null


export function useGetLangStrings<TData = Awaited<ReturnType<typeof getLangStrings>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLangStrings>>,
          TError,
          Awaited<ReturnType<typeof getLangStrings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLangStrings<TData = Awaited<ReturnType<typeof getLangStrings>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getLangStrings>>,
          TError,
          Awaited<ReturnType<typeof getLangStrings>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetLangStrings<TData = Awaited<ReturnType<typeof getLangStrings>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Traducciones
 */

export function useGetLangStrings<TData = Awaited<ReturnType<typeof getLangStrings>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getLangStrings>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetLangStringsQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene los diferentes códigos de estado utilizados en el sistema
 * @summary Códigos de Estado
 */
export const getStatusCodes = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetStatusCodes200>(
      {url: `/${idioma}/status-codes`, method: 'GET', signal
    },
      );
    }
  

export const getGetStatusCodesQueryKey = (idioma?: string,) => {
    return [`/${idioma}/status-codes`] as const;
    }

    
export const getGetStatusCodesQueryOptions = <TData = Awaited<ReturnType<typeof getStatusCodes>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetStatusCodesQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getStatusCodes>>> = ({ signal }) => getStatusCodes(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetStatusCodesQueryResult = NonNullable<Awaited<ReturnType<typeof getStatusCodes>>>
export type GetStatusCodesQueryError = null | null


export function useGetStatusCodes<TData = Awaited<ReturnType<typeof getStatusCodes>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatusCodes>>,
          TError,
          Awaited<ReturnType<typeof getStatusCodes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatusCodes<TData = Awaited<ReturnType<typeof getStatusCodes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getStatusCodes>>,
          TError,
          Awaited<ReturnType<typeof getStatusCodes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetStatusCodes<TData = Awaited<ReturnType<typeof getStatusCodes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Códigos de Estado
 */

export function useGetStatusCodes<TData = Awaited<ReturnType<typeof getStatusCodes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getStatusCodes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetStatusCodesQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Devuelve los documentos del voucher entregado
 * @summary Documentos del voucher
 */
export const getDocumentosVoucher = (
    idioma: string,
    voucher: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetDocumentosVoucher200>(
      {url: `/${idioma}/documentos/${voucher}`, method: 'GET', signal
    },
      );
    }
  

export const getGetDocumentosVoucherQueryKey = (idioma?: string,
    voucher?: string,) => {
    return [`/${idioma}/documentos/${voucher}`] as const;
    }

    
export const getGetDocumentosVoucherQueryOptions = <TData = Awaited<ReturnType<typeof getDocumentosVoucher>>, TError = null | null>(idioma: string,
    voucher: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDocumentosVoucherQueryKey(idioma,voucher);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDocumentosVoucher>>> = ({ signal }) => getDocumentosVoucher(idioma,voucher, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma && voucher), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDocumentosVoucherQueryResult = NonNullable<Awaited<ReturnType<typeof getDocumentosVoucher>>>
export type GetDocumentosVoucherQueryError = null | null


export function useGetDocumentosVoucher<TData = Awaited<ReturnType<typeof getDocumentosVoucher>>, TError = null | null>(
 idioma: string,
    voucher: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentosVoucher>>,
          TError,
          Awaited<ReturnType<typeof getDocumentosVoucher>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentosVoucher<TData = Awaited<ReturnType<typeof getDocumentosVoucher>>, TError = null | null>(
 idioma: string,
    voucher: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDocumentosVoucher>>,
          TError,
          Awaited<ReturnType<typeof getDocumentosVoucher>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDocumentosVoucher<TData = Awaited<ReturnType<typeof getDocumentosVoucher>>, TError = null | null>(
 idioma: string,
    voucher: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Documentos del voucher
 */

export function useGetDocumentosVoucher<TData = Awaited<ReturnType<typeof getDocumentosVoucher>>, TError = null | null>(
 idioma: string,
    voucher: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDocumentosVoucher>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDocumentosVoucherQueryOptions(idioma,voucher,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Devuelve los documentos de la busqueda, se puede buscar por voucher o por una combinación de nombre + apellido + (pasaporte o fecha de nacimiento)
 * @summary Buscar voucher
 */
export const getBuscarVoucher = (
    idioma: string,
    params?: GetBuscarVoucherParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetBuscarVoucher200>(
      {url: `/${idioma}/buscar_voucher`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetBuscarVoucherQueryKey = (idioma?: string,
    params?: GetBuscarVoucherParams,) => {
    return [`/${idioma}/buscar_voucher`, ...(params ? [params]: [])] as const;
    }

    
export const getGetBuscarVoucherQueryOptions = <TData = Awaited<ReturnType<typeof getBuscarVoucher>>, TError = null | null>(idioma: string,
    params?: GetBuscarVoucherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetBuscarVoucherQueryKey(idioma,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBuscarVoucher>>> = ({ signal }) => getBuscarVoucher(idioma,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetBuscarVoucherQueryResult = NonNullable<Awaited<ReturnType<typeof getBuscarVoucher>>>
export type GetBuscarVoucherQueryError = null | null


export function useGetBuscarVoucher<TData = Awaited<ReturnType<typeof getBuscarVoucher>>, TError = null | null>(
 idioma: string,
    params: undefined |  GetBuscarVoucherParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuscarVoucher>>,
          TError,
          Awaited<ReturnType<typeof getBuscarVoucher>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuscarVoucher<TData = Awaited<ReturnType<typeof getBuscarVoucher>>, TError = null | null>(
 idioma: string,
    params?: GetBuscarVoucherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getBuscarVoucher>>,
          TError,
          Awaited<ReturnType<typeof getBuscarVoucher>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetBuscarVoucher<TData = Awaited<ReturnType<typeof getBuscarVoucher>>, TError = null | null>(
 idioma: string,
    params?: GetBuscarVoucherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Buscar voucher
 */

export function useGetBuscarVoucher<TData = Awaited<ReturnType<typeof getBuscarVoucher>>, TError = null | null>(
 idioma: string,
    params?: GetBuscarVoucherParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getBuscarVoucher>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetBuscarVoucherQueryOptions(idioma,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Inicia la sesión de un agente
 * @summary Iniciar sesión
 */
export const postAgenteLogin = (
    idioma: string,
    postAgenteLoginBody: PostAgenteLoginBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<PostAgenteLogin200>(
      {url: `/${idioma}/login`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: postAgenteLoginBody, signal
    },
      );
    }
  


export const getPostAgenteLoginMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAgenteLogin>>, TError,{idioma: string;data: PostAgenteLoginBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postAgenteLogin>>, TError,{idioma: string;data: PostAgenteLoginBody}, TContext> => {

const mutationKey = ['postAgenteLogin'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postAgenteLogin>>, {idioma: string;data: PostAgenteLoginBody}> = (props) => {
          const {idioma,data} = props ?? {};

          return  postAgenteLogin(idioma,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostAgenteLoginMutationResult = NonNullable<Awaited<ReturnType<typeof postAgenteLogin>>>
    export type PostAgenteLoginMutationBody = PostAgenteLoginBody
    export type PostAgenteLoginMutationError = null | null

    /**
 * @summary Iniciar sesión
 */
export const usePostAgenteLogin = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postAgenteLogin>>, TError,{idioma: string;data: PostAgenteLoginBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postAgenteLogin>>,
        TError,
        {idioma: string;data: PostAgenteLoginBody},
        TContext
      > => {

      const mutationOptions = getPostAgenteLoginMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Cierra la sesión del usuario
 * @summary Cerrar Sesión
 */
export const postLogout = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<PostLogout200>(
      {url: `/${idioma}/logout`, method: 'POST', signal
    },
      );
    }
  


export const getPostLogoutMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,{idioma: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,{idioma: string}, TContext> => {

const mutationKey = ['postLogout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof postLogout>>, {idioma: string}> = (props) => {
          const {idioma} = props ?? {};

          return  postLogout(idioma,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PostLogoutMutationResult = NonNullable<Awaited<ReturnType<typeof postLogout>>>
    
    export type PostLogoutMutationError = null | null

    /**
 * @summary Cerrar Sesión
 */
export const usePostLogout = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof postLogout>>, TError,{idioma: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof postLogout>>,
        TError,
        {idioma: string},
        TContext
      > => {

      const mutationOptions = getPostLogoutMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Reporte de ventas por agencia (mes actual)
 * @summary Reporte de ventas por agencia
 */
export const getReporteVentasAgencia = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ReporteVentasAgenciaResponse>(
      {url: `/${idioma}/reporte-ventas-agencia`, method: 'GET', signal
    },
      );
    }
  

export const getGetReporteVentasAgenciaQueryKey = (idioma?: string,) => {
    return [`/${idioma}/reporte-ventas-agencia`] as const;
    }

    
export const getGetReporteVentasAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReporteVentasAgenciaQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReporteVentasAgencia>>> = ({ signal }) => getReporteVentasAgencia(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReporteVentasAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getReporteVentasAgencia>>>
export type GetReporteVentasAgenciaQueryError = null | null


export function useGetReporteVentasAgencia<TData = Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReporteVentasAgencia>>,
          TError,
          Awaited<ReturnType<typeof getReporteVentasAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReporteVentasAgencia<TData = Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReporteVentasAgencia>>,
          TError,
          Awaited<ReturnType<typeof getReporteVentasAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReporteVentasAgencia<TData = Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Reporte de ventas por agencia
 */

export function useGetReporteVentasAgencia<TData = Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReporteVentasAgenciaQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Reporte de ventas por agencia filtrado por mes y año (MM-YYYY)
 * @summary Reporte de ventas por agencia (filtrado)
 */
export const getReporteVentasAgenciaFiltrado = (
    idioma: string,
    mesAno: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ReporteVentasAgenciaResponse>(
      {url: `/${idioma}/reporte-ventas-agencia/${mesAno}`, method: 'GET', signal
    },
      );
    }
  

export const getGetReporteVentasAgenciaFiltradoQueryKey = (idioma?: string,
    mesAno?: string,) => {
    return [`/${idioma}/reporte-ventas-agencia/${mesAno}`] as const;
    }

    
export const getGetReporteVentasAgenciaFiltradoQueryOptions = <TData = Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError = null | null>(idioma: string,
    mesAno: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetReporteVentasAgenciaFiltradoQueryKey(idioma,mesAno);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>> = ({ signal }) => getReporteVentasAgenciaFiltrado(idioma,mesAno, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma && mesAno), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetReporteVentasAgenciaFiltradoQueryResult = NonNullable<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>>
export type GetReporteVentasAgenciaFiltradoQueryError = null | null


export function useGetReporteVentasAgenciaFiltrado<TData = Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError = null | null>(
 idioma: string,
    mesAno: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>,
          TError,
          Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReporteVentasAgenciaFiltrado<TData = Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError = null | null>(
 idioma: string,
    mesAno: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>,
          TError,
          Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetReporteVentasAgenciaFiltrado<TData = Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError = null | null>(
 idioma: string,
    mesAno: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Reporte de ventas por agencia (filtrado)
 */

export function useGetReporteVentasAgenciaFiltrado<TData = Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError = null | null>(
 idioma: string,
    mesAno: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getReporteVentasAgenciaFiltrado>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetReporteVentasAgenciaFiltradoQueryOptions(idioma,mesAno,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene el perfil del usuario autenticado
 * @summary Perfil de Agente
 */
export const getPerfilAgente = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetPerfilAgente200>(
      {url: `/${idioma}/perfil`, method: 'GET', signal
    },
      );
    }
  

export const getGetPerfilAgenteQueryKey = (idioma?: string,) => {
    return [`/${idioma}/perfil`] as const;
    }

    
export const getGetPerfilAgenteQueryOptions = <TData = Awaited<ReturnType<typeof getPerfilAgente>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPerfilAgenteQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPerfilAgente>>> = ({ signal }) => getPerfilAgente(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPerfilAgenteQueryResult = NonNullable<Awaited<ReturnType<typeof getPerfilAgente>>>
export type GetPerfilAgenteQueryError = null | null


export function useGetPerfilAgente<TData = Awaited<ReturnType<typeof getPerfilAgente>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPerfilAgente>>,
          TError,
          Awaited<ReturnType<typeof getPerfilAgente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPerfilAgente<TData = Awaited<ReturnType<typeof getPerfilAgente>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPerfilAgente>>,
          TError,
          Awaited<ReturnType<typeof getPerfilAgente>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPerfilAgente<TData = Awaited<ReturnType<typeof getPerfilAgente>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Perfil de Agente
 */

export function useGetPerfilAgente<TData = Awaited<ReturnType<typeof getPerfilAgente>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgente>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPerfilAgenteQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Actualiza el idioma preferido del agente autenticado
 * @summary Actualizar Idioma del Agente
 */
export const actualizarIdiomaAgente = (
    idioma: string,
    actualizarIdiomaAgenteBody: ActualizarIdiomaAgenteBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<ActualizarIdiomaAgente200>(
      {url: `/${idioma}/actualizar-idioma`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: actualizarIdiomaAgenteBody, signal
    },
      );
    }
  


export const getActualizarIdiomaAgenteMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarIdiomaAgente>>, TError,{idioma: string;data: ActualizarIdiomaAgenteBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof actualizarIdiomaAgente>>, TError,{idioma: string;data: ActualizarIdiomaAgenteBody}, TContext> => {

const mutationKey = ['actualizarIdiomaAgente'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof actualizarIdiomaAgente>>, {idioma: string;data: ActualizarIdiomaAgenteBody}> = (props) => {
          const {idioma,data} = props ?? {};

          return  actualizarIdiomaAgente(idioma,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type ActualizarIdiomaAgenteMutationResult = NonNullable<Awaited<ReturnType<typeof actualizarIdiomaAgente>>>
    export type ActualizarIdiomaAgenteMutationBody = ActualizarIdiomaAgenteBody
    export type ActualizarIdiomaAgenteMutationError = null | null

    /**
 * @summary Actualizar Idioma del Agente
 */
export const useActualizarIdiomaAgente = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof actualizarIdiomaAgente>>, TError,{idioma: string;data: ActualizarIdiomaAgenteBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof actualizarIdiomaAgente>>,
        TError,
        {idioma: string;data: ActualizarIdiomaAgenteBody},
        TContext
      > => {

      const mutationOptions = getActualizarIdiomaAgenteMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Devuelve la configuración de una página de cobranding para un idioma y URL específicos.
 * @summary Configuración de una página de cobranding
 */
export const getCobrandingConfig = (
    idioma: string,
    getCobrandingConfigBody: GetCobrandingConfigBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetCobrandingConfig200>(
      {url: `/${idioma}/cobranding`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getCobrandingConfigBody, signal
    },
      );
    }
  


export const getGetCobrandingConfigMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCobrandingConfig>>, TError,{idioma: string;data: GetCobrandingConfigBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getCobrandingConfig>>, TError,{idioma: string;data: GetCobrandingConfigBody}, TContext> => {

const mutationKey = ['getCobrandingConfig'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getCobrandingConfig>>, {idioma: string;data: GetCobrandingConfigBody}> = (props) => {
          const {idioma,data} = props ?? {};

          return  getCobrandingConfig(idioma,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetCobrandingConfigMutationResult = NonNullable<Awaited<ReturnType<typeof getCobrandingConfig>>>
    export type GetCobrandingConfigMutationBody = GetCobrandingConfigBody
    export type GetCobrandingConfigMutationError = null | null

    /**
 * @summary Configuración de una página de cobranding
 */
export const useGetCobrandingConfig = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getCobrandingConfig>>, TError,{idioma: string;data: GetCobrandingConfigBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getCobrandingConfig>>,
        TError,
        {idioma: string;data: GetCobrandingConfigBody},
        TContext
      > => {

      const mutationOptions = getGetCobrandingConfigMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Lista los vouchers master disponibles para el usuario autenticado
 * @summary Vouchers Master
 */
export const getVouchersMaster = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetVouchersMaster200>(
      {url: `/${idioma}/vouchers_master`, method: 'GET', signal
    },
      );
    }
  

export const getGetVouchersMasterQueryKey = (idioma?: string,) => {
    return [`/${idioma}/vouchers_master`] as const;
    }

    
export const getGetVouchersMasterQueryOptions = <TData = Awaited<ReturnType<typeof getVouchersMaster>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVouchersMasterQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVouchersMaster>>> = ({ signal }) => getVouchersMaster(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVouchersMasterQueryResult = NonNullable<Awaited<ReturnType<typeof getVouchersMaster>>>
export type GetVouchersMasterQueryError = null | null


export function useGetVouchersMaster<TData = Awaited<ReturnType<typeof getVouchersMaster>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVouchersMaster>>,
          TError,
          Awaited<ReturnType<typeof getVouchersMaster>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVouchersMaster<TData = Awaited<ReturnType<typeof getVouchersMaster>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVouchersMaster>>,
          TError,
          Awaited<ReturnType<typeof getVouchersMaster>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVouchersMaster<TData = Awaited<ReturnType<typeof getVouchersMaster>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Vouchers Master
 */

export function useGetVouchersMaster<TData = Awaited<ReturnType<typeof getVouchersMaster>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMaster>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVouchersMasterQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene el detalle de un voucher master específico (los vouchers ya creados del master enviado)
 * @summary Detalle de Voucher Master
 */
export const getVouchersMasterDetail = (
    idioma: string,
    idMaster: number,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetVouchersMasterDetail200>(
      {url: `/${idioma}/vouchers_master/${idMaster}`, method: 'GET', signal
    },
      );
    }
  

export const getGetVouchersMasterDetailQueryKey = (idioma?: string,
    idMaster?: number,) => {
    return [`/${idioma}/vouchers_master/${idMaster}`] as const;
    }

    
export const getGetVouchersMasterDetailQueryOptions = <TData = Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError = null | null>(idioma: string,
    idMaster: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetVouchersMasterDetailQueryKey(idioma,idMaster);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getVouchersMasterDetail>>> = ({ signal }) => getVouchersMasterDetail(idioma,idMaster, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma && idMaster), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetVouchersMasterDetailQueryResult = NonNullable<Awaited<ReturnType<typeof getVouchersMasterDetail>>>
export type GetVouchersMasterDetailQueryError = null | null


export function useGetVouchersMasterDetail<TData = Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError = null | null>(
 idioma: string,
    idMaster: number, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVouchersMasterDetail>>,
          TError,
          Awaited<ReturnType<typeof getVouchersMasterDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVouchersMasterDetail<TData = Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError = null | null>(
 idioma: string,
    idMaster: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getVouchersMasterDetail>>,
          TError,
          Awaited<ReturnType<typeof getVouchersMasterDetail>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetVouchersMasterDetail<TData = Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError = null | null>(
 idioma: string,
    idMaster: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Detalle de Voucher Master
 */

export function useGetVouchersMasterDetail<TData = Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError = null | null>(
 idioma: string,
    idMaster: number, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getVouchersMasterDetail>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetVouchersMasterDetailQueryOptions(idioma,idMaster,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Lista las renovaciones pendientes para el usuario autenticado
 * @summary Renovaciones Pendientes
 */
export const getRenovacionesPendientes = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetRenovacionesPendientes200>(
      {url: `/${idioma}/renovaciones-pendientes`, method: 'GET', signal
    },
      );
    }
  

export const getGetRenovacionesPendientesQueryKey = (idioma?: string,) => {
    return [`/${idioma}/renovaciones-pendientes`] as const;
    }

    
export const getGetRenovacionesPendientesQueryOptions = <TData = Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetRenovacionesPendientesQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRenovacionesPendientes>>> = ({ signal }) => getRenovacionesPendientes(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetRenovacionesPendientesQueryResult = NonNullable<Awaited<ReturnType<typeof getRenovacionesPendientes>>>
export type GetRenovacionesPendientesQueryError = null | null


export function useGetRenovacionesPendientes<TData = Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRenovacionesPendientes>>,
          TError,
          Awaited<ReturnType<typeof getRenovacionesPendientes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRenovacionesPendientes<TData = Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getRenovacionesPendientes>>,
          TError,
          Awaited<ReturnType<typeof getRenovacionesPendientes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetRenovacionesPendientes<TData = Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Renovaciones Pendientes
 */

export function useGetRenovacionesPendientes<TData = Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getRenovacionesPendientes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetRenovacionesPendientesQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Desactiva el recordatorio de renovación para el usuario indicado.
 * @summary Detener Recordatorio Renovación
 */
export const detenerRecordatorioRenovacion = (
    idioma: string,
    detenerRecordatorioRenovacionBody: DetenerRecordatorioRenovacionBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<DetenerRecordatorioRenovacion200>(
      {url: `/${idioma}/detener_recordatorio_renovacion`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: detenerRecordatorioRenovacionBody, signal
    },
      );
    }
  


export const getDetenerRecordatorioRenovacionMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>, TError,{idioma: string;data: DetenerRecordatorioRenovacionBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>, TError,{idioma: string;data: DetenerRecordatorioRenovacionBody}, TContext> => {

const mutationKey = ['detenerRecordatorioRenovacion'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>, {idioma: string;data: DetenerRecordatorioRenovacionBody}> = (props) => {
          const {idioma,data} = props ?? {};

          return  detenerRecordatorioRenovacion(idioma,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DetenerRecordatorioRenovacionMutationResult = NonNullable<Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>>
    export type DetenerRecordatorioRenovacionMutationBody = DetenerRecordatorioRenovacionBody
    export type DetenerRecordatorioRenovacionMutationError = null | null

    /**
 * @summary Detener Recordatorio Renovación
 */
export const useDetenerRecordatorioRenovacion = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>, TError,{idioma: string;data: DetenerRecordatorioRenovacionBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof detenerRecordatorioRenovacion>>,
        TError,
        {idioma: string;data: DetenerRecordatorioRenovacionBody},
        TContext
      > => {

      const mutationOptions = getDetenerRecordatorioRenovacionMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Lista los agentes de una agencia
 * @summary Agentes de Agencia
 */
export const getAgentesAgencia = (
    idioma: string,
    params: GetAgentesAgenciaParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetAgentesAgencia200>(
      {url: `/${idioma}/agentes`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetAgentesAgenciaQueryKey = (idioma?: string,
    params?: GetAgentesAgenciaParams,) => {
    return [`/${idioma}/agentes`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAgentesAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getAgentesAgencia>>, TError = null | null>(idioma: string,
    params: GetAgentesAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgentesAgenciaQueryKey(idioma,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgentesAgencia>>> = ({ signal }) => getAgentesAgencia(idioma,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgentesAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getAgentesAgencia>>>
export type GetAgentesAgenciaQueryError = null | null


export function useGetAgentesAgencia<TData = Awaited<ReturnType<typeof getAgentesAgencia>>, TError = null | null>(
 idioma: string,
    params: GetAgentesAgenciaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentesAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAgentesAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentesAgencia<TData = Awaited<ReturnType<typeof getAgentesAgencia>>, TError = null | null>(
 idioma: string,
    params: GetAgentesAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgentesAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAgentesAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgentesAgencia<TData = Awaited<ReturnType<typeof getAgentesAgencia>>, TError = null | null>(
 idioma: string,
    params: GetAgentesAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Agentes de Agencia
 */

export function useGetAgentesAgencia<TData = Awaited<ReturnType<typeof getAgentesAgencia>>, TError = null | null>(
 idioma: string,
    params: GetAgentesAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgentesAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgentesAgenciaQueryOptions(idioma,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Lista las agencias de una agencia
 * @summary Agencias de Agencia
 */
export const getAgenciasAgencia = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetAgenciasAgencia200>(
      {url: `/${idioma}/agencias`, method: 'GET', signal
    },
      );
    }
  

export const getGetAgenciasAgenciaQueryKey = (idioma?: string,) => {
    return [`/${idioma}/agencias`] as const;
    }

    
export const getGetAgenciasAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getAgenciasAgencia>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAgenciasAgenciaQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAgenciasAgencia>>> = ({ signal }) => getAgenciasAgencia(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAgenciasAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getAgenciasAgencia>>>
export type GetAgenciasAgenciaQueryError = null | null


export function useGetAgenciasAgencia<TData = Awaited<ReturnType<typeof getAgenciasAgencia>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgenciasAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAgenciasAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgenciasAgencia<TData = Awaited<ReturnType<typeof getAgenciasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAgenciasAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAgenciasAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAgenciasAgencia<TData = Awaited<ReturnType<typeof getAgenciasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Agencias de Agencia
 */

export function useGetAgenciasAgencia<TData = Awaited<ReturnType<typeof getAgenciasAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAgenciasAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAgenciasAgenciaQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Obtiene el perfil de la agencia autenticada
 * @summary Perfil de Agencia
 */
export const getPerfilAgencia = (
    idioma: string,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetPerfilAgencia200>(
      {url: `/${idioma}/perfil-agencia`, method: 'GET', signal
    },
      );
    }
  

export const getGetPerfilAgenciaQueryKey = (idioma?: string,) => {
    return [`/${idioma}/perfil-agencia`] as const;
    }

    
export const getGetPerfilAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getPerfilAgencia>>, TError = null | null>(idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPerfilAgenciaQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPerfilAgencia>>> = ({ signal }) => getPerfilAgencia(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPerfilAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getPerfilAgencia>>>
export type GetPerfilAgenciaQueryError = null | null


export function useGetPerfilAgencia<TData = Awaited<ReturnType<typeof getPerfilAgencia>>, TError = null | null>(
 idioma: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPerfilAgencia>>,
          TError,
          Awaited<ReturnType<typeof getPerfilAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPerfilAgencia<TData = Awaited<ReturnType<typeof getPerfilAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPerfilAgencia>>,
          TError,
          Awaited<ReturnType<typeof getPerfilAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPerfilAgencia<TData = Awaited<ReturnType<typeof getPerfilAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Perfil de Agencia
 */

export function useGetPerfilAgencia<TData = Awaited<ReturnType<typeof getPerfilAgencia>>, TError = null | null>(
 idioma: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPerfilAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPerfilAgenciaQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Lista las cotizaciones del agente o agencia autenticada
 * @summary Cotizaciones de Agente / Agencia
 */
export const getCotizacionesAgenteAgencia = (
    idioma: string,
    params?: GetCotizacionesAgenteAgenciaParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetCotizacionesAgenteAgencia200>(
      {url: `/${idioma}/cotizaciones`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetCotizacionesAgenteAgenciaQueryKey = (idioma?: string,
    params?: GetCotizacionesAgenteAgenciaParams,) => {
    return [`/${idioma}/cotizaciones`, ...(params ? [params]: [])] as const;
    }

    
export const getGetCotizacionesAgenteAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError = null | null>(idioma: string,
    params?: GetCotizacionesAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetCotizacionesAgenteAgenciaQueryKey(idioma,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>> = ({ signal }) => getCotizacionesAgenteAgencia(idioma,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetCotizacionesAgenteAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>>
export type GetCotizacionesAgenteAgenciaQueryError = null | null


export function useGetCotizacionesAgenteAgencia<TData = Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params: undefined |  GetCotizacionesAgenteAgenciaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>,
          TError,
          Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCotizacionesAgenteAgencia<TData = Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetCotizacionesAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>,
          TError,
          Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetCotizacionesAgenteAgencia<TData = Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetCotizacionesAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Cotizaciones de Agente / Agencia
 */

export function useGetCotizacionesAgenteAgencia<TData = Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetCotizacionesAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getCotizacionesAgenteAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetCotizacionesAgenteAgenciaQueryOptions(idioma,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Lista las asistencias del agente o agencia autenticada
 * @summary Asistencias del Agente / Agencia
 */
export const getAsistenciasAgenteAgencia = (
    idioma: string,
    params?: GetAsistenciasAgenteAgenciaParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetAsistenciasAgenteAgencia200>(
      {url: `/${idioma}/asistencias`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetAsistenciasAgenteAgenciaQueryKey = (idioma?: string,
    params?: GetAsistenciasAgenteAgenciaParams,) => {
    return [`/${idioma}/asistencias`, ...(params ? [params]: [])] as const;
    }

    
export const getGetAsistenciasAgenteAgenciaQueryOptions = <TData = Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError = null | null>(idioma: string,
    params?: GetAsistenciasAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAsistenciasAgenteAgenciaQueryKey(idioma,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>> = ({ signal }) => getAsistenciasAgenteAgencia(idioma,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetAsistenciasAgenteAgenciaQueryResult = NonNullable<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>>
export type GetAsistenciasAgenteAgenciaQueryError = null | null


export function useGetAsistenciasAgenteAgencia<TData = Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params: undefined |  GetAsistenciasAgenteAgenciaParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAsistenciasAgenteAgencia<TData = Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetAsistenciasAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>,
          TError,
          Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetAsistenciasAgenteAgencia<TData = Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetAsistenciasAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Asistencias del Agente / Agencia
 */

export function useGetAsistenciasAgenteAgencia<TData = Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError = null | null>(
 idioma: string,
    params?: GetAsistenciasAgenteAgenciaParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getAsistenciasAgenteAgencia>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetAsistenciasAgenteAgenciaQueryOptions(idioma,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Registra un lead de evento
 * @summary Lead
 */
export const getLeadEvento = (
    idioma: string,
    getLeadEventoBody: GetLeadEventoBody,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetLeadEvento200>(
      {url: `/${idioma}/lead_evento`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: getLeadEventoBody, signal
    },
      );
    }
  


export const getGetLeadEventoMutationOptions = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeadEvento>>, TError,{idioma: string;data: GetLeadEventoBody}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof getLeadEvento>>, TError,{idioma: string;data: GetLeadEventoBody}, TContext> => {

const mutationKey = ['getLeadEvento'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof getLeadEvento>>, {idioma: string;data: GetLeadEventoBody}> = (props) => {
          const {idioma,data} = props ?? {};

          return  getLeadEvento(idioma,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type GetLeadEventoMutationResult = NonNullable<Awaited<ReturnType<typeof getLeadEvento>>>
    export type GetLeadEventoMutationBody = GetLeadEventoBody
    export type GetLeadEventoMutationError = null | null

    /**
 * @summary Lead
 */
export const useGetLeadEvento = <TError = null | null,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof getLeadEvento>>, TError,{idioma: string;data: GetLeadEventoBody}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof getLeadEvento>>,
        TError,
        {idioma: string;data: GetLeadEventoBody},
        TContext
      > => {

      const mutationOptions = getGetLeadEventoMutationOptions(options);

      return useMutation(mutationOptions , queryClient);
    }
    
/**
 * Devuelve un listado de clientes con información básica.
 * @summary Listado de Clientes
 */
export const getClientes = (
    idioma: string,
    params?: GetClientesParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetClientes200>(
      {url: `/${idioma}/clientes`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetClientesQueryKey = (idioma?: string,
    params?: GetClientesParams,) => {
    return [`/${idioma}/clientes`, ...(params ? [params]: [])] as const;
    }

    
export const getGetClientesQueryOptions = <TData = Awaited<ReturnType<typeof getClientes>>, TError = null | null>(idioma: string,
    params?: GetClientesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClientesQueryKey(idioma,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClientes>>> = ({ signal }) => getClientes(idioma,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClientesQueryResult = NonNullable<Awaited<ReturnType<typeof getClientes>>>
export type GetClientesQueryError = null | null


export function useGetClientes<TData = Awaited<ReturnType<typeof getClientes>>, TError = null | null>(
 idioma: string,
    params: undefined |  GetClientesParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientes>>,
          TError,
          Awaited<ReturnType<typeof getClientes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientes<TData = Awaited<ReturnType<typeof getClientes>>, TError = null | null>(
 idioma: string,
    params?: GetClientesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClientes>>,
          TError,
          Awaited<ReturnType<typeof getClientes>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClientes<TData = Awaited<ReturnType<typeof getClientes>>, TError = null | null>(
 idioma: string,
    params?: GetClientesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Listado de Clientes
 */

export function useGetClientes<TData = Awaited<ReturnType<typeof getClientes>>, TError = null | null>(
 idioma: string,
    params?: GetClientesParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClientes>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClientesQueryOptions(idioma,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Devuelve un listado de ventas asociadas a un cliente específico, incluyendo detalles de los documentos y paginación.
 * @summary Ventas por Cliente
 */
export const getClienteVentas = (
    idioma: 'es' | 'en',
    clienteId: string,
    params?: GetClienteVentasParams,
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetClienteVentas200>(
      {url: `/${idioma}/cliente-ventas/${clienteId}`, method: 'GET',
        params, signal
    },
      );
    }
  

export const getGetClienteVentasQueryKey = (idioma?: 'es' | 'en',
    clienteId?: string,
    params?: GetClienteVentasParams,) => {
    return [`/${idioma}/cliente-ventas/${clienteId}`, ...(params ? [params]: [])] as const;
    }

    
export const getGetClienteVentasQueryOptions = <TData = Awaited<ReturnType<typeof getClienteVentas>>, TError = null | null | null>(idioma: 'es' | 'en',
    clienteId: string,
    params?: GetClienteVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetClienteVentasQueryKey(idioma,clienteId,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getClienteVentas>>> = ({ signal }) => getClienteVentas(idioma,clienteId,params, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma && clienteId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetClienteVentasQueryResult = NonNullable<Awaited<ReturnType<typeof getClienteVentas>>>
export type GetClienteVentasQueryError = null | null | null


export function useGetClienteVentas<TData = Awaited<ReturnType<typeof getClienteVentas>>, TError = null | null | null>(
 idioma: 'es' | 'en',
    clienteId: string,
    params: undefined |  GetClienteVentasParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClienteVentas>>,
          TError,
          Awaited<ReturnType<typeof getClienteVentas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClienteVentas<TData = Awaited<ReturnType<typeof getClienteVentas>>, TError = null | null | null>(
 idioma: 'es' | 'en',
    clienteId: string,
    params?: GetClienteVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getClienteVentas>>,
          TError,
          Awaited<ReturnType<typeof getClienteVentas>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetClienteVentas<TData = Awaited<ReturnType<typeof getClienteVentas>>, TError = null | null | null>(
 idioma: 'es' | 'en',
    clienteId: string,
    params?: GetClienteVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Ventas por Cliente
 */

export function useGetClienteVentas<TData = Awaited<ReturnType<typeof getClienteVentas>>, TError = null | null | null>(
 idioma: 'es' | 'en',
    clienteId: string,
    params?: GetClienteVentasParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getClienteVentas>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetClienteVentasQueryOptions(idioma,clienteId,params,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Devuelve los datos agregados del dashboard para el usuario autenticado.
 * @summary Dashboard principal
 */
export const getDashboard = (
    idioma: 'es' | 'en',
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetDashboard200>(
      {url: `/${idioma}/dashboard`, method: 'GET', signal
    },
      );
    }
  

export const getGetDashboardQueryKey = (idioma?: 'es' | 'en',) => {
    return [`/${idioma}/dashboard`] as const;
    }

    
export const getGetDashboardQueryOptions = <TData = Awaited<ReturnType<typeof getDashboard>>, TError = null | null>(idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetDashboardQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getDashboard>>> = ({ signal }) => getDashboard(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetDashboardQueryResult = NonNullable<Awaited<ReturnType<typeof getDashboard>>>
export type GetDashboardQueryError = null | null


export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = null | null>(
 idioma: 'es' | 'en', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboard>>,
          TError,
          Awaited<ReturnType<typeof getDashboard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getDashboard>>,
          TError,
          Awaited<ReturnType<typeof getDashboard>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Dashboard principal
 */

export function useGetDashboard<TData = Awaited<ReturnType<typeof getDashboard>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getDashboard>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetDashboardQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * Devuelve la tasa de comisiones por tipo de plan para el usuario autenticado.
 * @summary Tasa de comisiones
 */
export const getTasaComisiones = (
    idioma: 'es' | 'en',
 signal?: AbortSignal
) => {
      
      
      return customFetch<GetTasaComisiones200>(
      {url: `/${idioma}/tasa-comisiones`, method: 'GET', signal
    },
      );
    }
  

export const getGetTasaComisionesQueryKey = (idioma?: 'es' | 'en',) => {
    return [`/${idioma}/tasa-comisiones`] as const;
    }

    
export const getGetTasaComisionesQueryOptions = <TData = Awaited<ReturnType<typeof getTasaComisiones>>, TError = null | null>(idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetTasaComisionesQueryKey(idioma);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getTasaComisiones>>> = ({ signal }) => getTasaComisiones(idioma, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(idioma), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetTasaComisionesQueryResult = NonNullable<Awaited<ReturnType<typeof getTasaComisiones>>>
export type GetTasaComisionesQueryError = null | null


export function useGetTasaComisiones<TData = Awaited<ReturnType<typeof getTasaComisiones>>, TError = null | null>(
 idioma: 'es' | 'en', options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasaComisiones>>,
          TError,
          Awaited<ReturnType<typeof getTasaComisiones>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasaComisiones<TData = Awaited<ReturnType<typeof getTasaComisiones>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getTasaComisiones>>,
          TError,
          Awaited<ReturnType<typeof getTasaComisiones>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetTasaComisiones<TData = Awaited<ReturnType<typeof getTasaComisiones>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Tasa de comisiones
 */

export function useGetTasaComisiones<TData = Awaited<ReturnType<typeof getTasaComisiones>>, TError = null | null>(
 idioma: 'es' | 'en', options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getTasaComisiones>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetTasaComisionesQueryOptions(idioma,options)

  const query = useQuery(queryOptions , queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




