/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * WAC API
 * Api para uso interno WAC.
 * OpenAPI spec version: 1.0.0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  GetIdiomaDocumentosVoucher200,
  GetIdiomaLangStrings200,
  GetIdiomaTiposPlanes200,
  GetIdiomas200
} from './schemas';

export const getWacApi = () => {
/**
 * @summary Los idiomas que tiene el Sitio
 */
const getIdiomas = <TData = AxiosResponse<GetIdiomas200>>(
     options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/idiomas`,options
    );
  }

/**
 * @summary Las traducciones del idioma
 */
const getIdiomaLangStrings = <TData = AxiosResponse<GetIdiomaLangStrings200>>(
    idioma: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/${idioma}/lang_strings`,options
    );
  }

/**
 * @summary Devuelve los documentos del voucher entregado
 */
const getIdiomaDocumentosVoucher = <TData = AxiosResponse<GetIdiomaDocumentosVoucher200>>(
    idioma: string,
    voucher: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/${idioma}/documentos/${voucher}`,options
    );
  }

/**
 * Retorna una lista de tipos de planes disponibles en el idioma especificado. Si el idioma no es válido, se informa el error. Si el usuario está autenticado, se incluye también información del agente.
 * @summary Devuelve los tipos de planes
 */
const getIdiomaTiposPlanes = <TData = AxiosResponse<GetIdiomaTiposPlanes200>>(
    idioma: string, options?: AxiosRequestConfig
 ): Promise<TData> => {
    return axios.default.get(
      `/${idioma}/tipos_planes`,options
    );
  }

return {getIdiomas,getIdiomaLangStrings,getIdiomaDocumentosVoucher,getIdiomaTiposPlanes}};
export type GetIdiomasResult = AxiosResponse<GetIdiomas200>
export type GetIdiomaLangStringsResult = AxiosResponse<GetIdiomaLangStrings200>
export type GetIdiomaDocumentosVoucherResult = AxiosResponse<GetIdiomaDocumentosVoucher200>
export type GetIdiomaTiposPlanesResult = AxiosResponse<GetIdiomaTiposPlanes200>
